config/routes.rb
Rails.application.routes.draw do
  root "publics#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :publics, only: [:index]
  resources :trips do
    resources :stops, only: [:new, :create, :edit, :update, :destroy]
    resource :trip_groups, only: [:show, :create, :destroy]
    resource :archives, only: [:create, :destroy]
  end

  resources :stops, only: [:new, :create, :edit, :update, :destroy] do
    resource :stop_orders, only: [:edit, :update]
  end

  resources :locations, only: [:new, :create]
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  validates :starts_on, presence: true
  validates :city, presence: true

  has_many :trip_groups
  has_many :users, through: :trip_groups

  has_many :stops
  has_many :locations, through: :stops

  belongs_to :owner, class_name: "User"

  default_scope { order(:starts_on) }

  def update_stop_order_after(stop, proposed_order)
    stop_ids_in_order = stops.sort_by(&:order).map(&:id)

    stop_id_to_update = stop_ids_in_order.delete(stop.id)

    new_stop_ids_in_order = stop_ids_in_order.insert(proposed_order - 1,
                                                     stop_id_to_update)

    new_stop_ids_in_order.each_with_index do |id, index|
      stops.find(id).update(order: index + 1)
    end
  end

  def update_stops_after(deleted_stop)
    stops.each do |stop|
      if stop.order > deleted_stop.order
        stop.update(order: stop.order - 1)
      end
    end
  end

  def shared_users_except(user)
    users.where.not(id: user.id)
  end

  def unshared_users
    shared_user_ids = users.pluck(:id)
    User.where.not(id: shared_user_ids)
  end

  def shared_to?(user)
    users.include?(user)
  end

  private

  def get_ordered_stops_ids
    stop_ids = stops.pluck(:id)
    stop_orders = stops.pluck(:order)
    hash = {}

    stop_ids.count.times do |i|
      hash[stop_orders[i]] = stop_ids[i]
    end

    hash.sort.to_h.values
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :require_ownership, only: [:edit, :update, :destroy]

  def index
    @incoming_trips = current_user.incoming_trips
    @archived_trips = current_user.archived_trips
    @trip = current_user.trips.new
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.save
      current_user.trips << @trip
      redirect_to trips_path
    else
      render :new
    end
  end

  def show
    @trip = load_trip_from_url
    @stop = @trip.stops.new
    @location = Location.new
  end

  def edit
    @trip = load_trip_from_url
  end

  def update
    @trip = load_trip_from_url
    if @trip.update(trip_params)
      redirect_to @trip
    else
      render :edit
    end
  end

  def destroy
    trip = load_trip_from_url
    current_user.trips.destroy(trip)
    redirect_to trips_path
  end

  private

  def load_trip_from_url
    current_user.trips.find(params[:id])
  end

  def trip_params
    params.require(:trip).
      permit(:starts_on, :city, :completed).
      merge(owner_id: current_user.id)
  end

  def require_ownership
    trip = Trip.find(params[:id])
    require_owner(trip)
  end
end

app/views/trips/_archive_button.html.erb
<% if trip.completed %>
  <%= button_to "Unarchive", trip_archives_path(trip), method: :delete,
    class: "archive-button"%>
<% else %>
  <%= button_to "Archive", trip_archives_path(trip), class: "archive-button" %>
<% end %>

app/views/trips/_form.html.erb
<%= render "error_messages", target: trip %>

<%= form_for trip do |form| %>
  <%= form.label :starts_on %>
  <%= form.datetime_local_field :starts_on %>

  <%= form.label :city %>
  <%= form.text_field :city %>

  <%= form.submit %>
<% end %>

app/views/trips/_trip.html.erb
<tr class="trip-row td-row">
  <td><%= trip.starts_on.to_date %></td>
  <td class="starts_at"><%= trip.starts_on.strftime("%H : %M") %></td>
  <td class="estimated-total-time"></td>
  <td class="trip-city"><%= link_to trip.city, trip %></td>
  <td>
    <% if current_user.owner?(trip) %>
      <% if trip.completed %>
        <%= button_to "Unarchive", trip_archives_path(trip), method: :delete %>
      <% else %>
        <%= button_to "Archive", trip_archives_path(trip) %>
      <% end %>
    <% end %>
  </td>

  <% if current_user.id == trip.owner_id %>
    <td>
      <%= link_to "Edit", edit_trip_path(trip) %>
    </td>
    <td>
      <%= button_to "Delete", trip, method: :delete %>
    </td>
  <% end %>
</tr>

app/views/trips/edit.html.erb
<div class="edit-trip main-box">
  <h3>Edit trip to <%= @trip.city %></h3>

  <%= render "form", trip: @trip %>
</div>

app/views/trips/index.html.erb
<%= content_for :scripts do %>
  <%= javascript_include_tag "toggle_new_trip.js" %>
<% end %>

<div class="incoming-trip main-box">
  <h3>Incoming Trip</h3>

  <table>
    <tr>
      <th>Date</th>
      <th>Starts</th>
      <th>Estimated Ends (Total Time)</th>
      <th>Place</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <%= render @incoming_trips %>
  </table>
</div>

<div class="archived-trip main-box">
  <h3>Archived Trip</h3>

  <table>
    <tr>
      <th>Date</th>
      <th>Starts</th>
      <th>Estimated Ends (Total Time)</th>
      <th>Place</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <%= render @archived_trips %>
  </table>
</div>

<div class="new-trip main-box">
  <h3>Create a trip</h3>

  <div class="new-trip-form">
    <%= render "form", trip: @trip %>
  </div>
</div>

app/views/trips/show.html.erb
<%= content_for :scripts do %>
  <%= javascript_include_tag "map.js",
    "add_location.js",
    "add_stop.js",
    "delete_stop.js",
    "scroll_screen.js",
    "toggle_new_location_stop.js",
    "update_stay_time.js",
    "update_stop.js",
    "update_table_and_map.js" %>
<% end %>

<div class="trip-overview main-box">
  <h3>Trip to <%= @trip.city %> ( <%= @trip.starts_on %> )</h3>

  <table>
    <tr>
      <th>Date</th>
      <th>Starts</th>
      <th>Estimated Ends (Total Time)</th>
      <th>Place</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <tr><%= render @trip %></tr>
  </table>

  <h4>
    <%= link_to "Share to friends", trip_trip_groups_path(@trip),
      class: "share-link" %>
  </h4>
</div>

<% if current_user.owner?(@trip) %>
  <div class="new-location-stop main-box">
    <h3>Create location and add stop</h3>

    <div class="create-location new-location-stop-form">
      <p><strong>Create a location</strong></p>
      <div class="location-errors"></div>
      <div class="location-form">
        <%= render "locations/form", location: @location %>
      </div>
    </div>

    <div class="add-stop new-location-stop-form">
      <p><strong>Add a stop</strong></p>
      <div class="stop-errors"></div>
      <div class="stop-form">
        <%= render "stops/form", trip: @trip, stop: @stop %>
      </div>
    </div>
  </div>
<% end %>

<div class="all-locations-stops main-box">
  <h3>View all locations and stops</h3>
  <p><%= image_tag("add_stop.png", class: "add-stop-image") %> Add more stop</p>

  <table class="trip-table">
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>Address</th>
      <th>Duration (min)</th>
      <th>To Next Stop<br/>(min (mi))</th>
      <th></th>
    </tr>

    <%= render @trip.stops.all %>
  </table>

  <div class="mode-select">
    <p class="mode-select">Select Mode:
    <%= mode_select %>
    </p>
  </div>
</div>

<div class="map main-box">
  <div id="map-canvas"></div>
</div>