config/routes.rb
Rails.application.routes.draw do
  root "publics#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :publics, only: [:index]
  resources :trips do
    resources :stops, only: [:new, :create, :edit, :update, :destroy]
    resource :trip_groups, only: [:show, :create, :destroy]
    resource :archives, only: [:create, :destroy]
  end

  resources :stops, only: [:new, :create, :edit, :update, :destroy] do
    resource :stop_orders, only: [:edit, :update]
  end

  resources :locations, only: [:new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripmap</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?libraries=geometry?
    sensor=false&libraries=places&dummy=.js?
    key=AIzaSyAQ4_p1yfXKUuWWQsOAFWN52wyOXz8K81E">
  </script>
  <%= javascript_include_tag 'application' %>
  <%= yield :scripts %>
</head>
<body>
  <div class="header">
    <div class="header-container">
      <div class="header-logo"></div>

      <div class="header-title">
        <%= link_to "TripMap", root_path, class: "header-title-link" %>
      </div>

      <% if signed_in? %>
        <div class="header-nav left">
          <ul class="header-nav-list">
            <li class="header-nav-item">
            <%= link_to "My Trips", trips_path, class: "header-nav-link" %>
            </li>
          </ul>
        </div>
      <% end %>

      <div class="header-nav right">
        <ul class="header-nav-list">
          <% if signed_in? %>
            <li class="header-nav-item">
              <%= current_user.email %>
            </li>
            <li class="header-nav-item">
            <%= link_to "Sign out", session_path, method: :delete, class:
              "header-nav-link" %>
            </li>
          <% else %>
            <li class="header-nav-item">
            <%= link_to "Sign in", new_session_path, class:
              "header-nav-link" %>
            </li>
            <li class="header-nav-item">
              <%= link_to "Sign up", new_user_path, class: "header-nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="clear"></div>
    </div>
  </div>

  <div class="main">
    <div class="public">
      <%= yield :public %>
    </div>
    <div class="main-container">
      <%= yield %>
    </div>

    <div class="clear"></div>
  </div>

  <div class="footer">
    <div class="footer-container">
      <div class="footer-nav right">
        <ul class="footer-nav-list">
          <li class="footer-nav-item">
          © 2014 TripMap
          </li>
        </ul>
      </div>

      <div class="clear"></div>
    </div>
  </div>
</body>
</html>